# Generated by Django 5.2.4 on 2025-07-23 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tool_app_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('github_repo', models.URLField(blank=True)),
                ('demo_link', models.URLField(blank=True)),
                ('tutorial_link', models.URLField(blank=True)),
                ('technologies', models.CharField(help_text='Comma-separated technologies', max_length=500)),
                ('hours_worked', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('in_dev', 'In Development'), ('ready', 'Ready to Use'), ('shipped', 'Shipped')], default='in_dev', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
